name: Tests

on:
  push:
    branch: main

# permissions:
#   contents: read
#   pages: write
#   id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install modules âš™ï¸
        run: npm ci

      - name: Bot notify - Tests STARTS âœ‰ï¸
        run: 'curl -X GET https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendMessage -H "Content-Type: application/json" -d ''{"chat_id": "${{secrets.CHAT_ID}}","text": "Tests STARTS!"}'''

      - name: Run tests ğŸ§¬
        continue-on-error: true
        run: npm test

      - name: Bot notify - Tests DONE âœ‰ï¸
        run: 'curl -X GET https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendMessage -H "Content-Type: application/json" -d ''{"chat_id": "${{secrets.CHAT_ID}}","text": "Testing DONE!"}'''

      - name: Use the upload artifact GitHub Action ğŸ“¦
        uses: actions/upload-artifact@v3
        with:
          name: report
          if-no-files-found: error
          path: |
            report.html
            jest-html-reporters-attach

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: jest-html-reporters-attach
